export const ScreenName = {
  homeNavigator: 'HomeNavigator',
  shopNavigator: 'ShopNavigator',
  cartNavigator: 'CartNavigator',
  favoriteNavigator: 'FavoriteNavigator',
  profileNavigator: 'ProfileNavigator',
  testComponent: 'TestComponent',
  loginScreen: 'LoginScreen',
  signupScreen: 'SignupScreen',
  forgotPassScreen: 'ForgotPassScreen',
  homeScreen: 'HomeScreen',
  categoriesScreen: 'CategoriesScreen',
  partialCategoryScreen: 'PartialCategoryScreen',
  catalogScreen: 'CatalogScreen',
  filterModals: 'FilterModals',
  brandModals: 'BrandModals',
  productCardScreen: 'ProductCardScreen',
  favoriteScreen: 'FavoriteScreen',
  cartScreen: 'CartScreen',
};
